# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Название'),
        ),
    ]
