# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20170222_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Удален?'),
        ),
    ]
